a =10
b = 13

c = 0

def tohex(val, t):
    
  return format((val + (1 << 32)) % (1 << 32), t)

print('op1 <= x"' + tohex(a, '08x') +'";')
print('op2 <= x"' + tohex(b, '08x') +'";')

print("op_code <=s_and;")
print("wait for 10 ns;")
print('assert res = x"' + tohex(a & b, '08x') +'" report "Fail" severity error;')
print("op_code <=s_eor;")
print("wait for 10 ns;")
print('assert res = x"' + tohex(a ^ b, '08x') +'" report "Fail" severity error;')
print("op_code <=s_sub;")
print("wait for 10 ns;")
print('assert res = x"' + tohex(a-b, '08x') +'" report "Fail" severity error;')
print("op_code <=s_rsb;")
print("wait for 10 ns;")
print('assert res = x"' + tohex(b-a, '08x') +'" report "Fail" severity error;')
print("op_code <=s_add;")
print("wait for 10 ns;")
print('assert res = x"' + tohex(a+b, '08x') +'" report "Fail" severity error;')
print("op_code <=s_adc;")
print("wait for 10 ns;")
print('assert res = x"' + tohex(a+b +c, '08x') +'" report "Fail" severity error;')
print("op_code <=s_sbc;")
print("wait for 10 ns;")
print('assert res = x"' + tohex(a + ~b +c, '08x') +'" report "Fail" severity error;')
print("op_code <=s_rsc;")
print("wait for 10 ns;")
print('assert res = x"' + tohex(~a + b +c, '08x') +'" report "Fail" severity error;')
print("op_code <=s_tst;")
print("wait for 10 ns;")
print('assert res = x"' + tohex(a & b , '08x') +'" report "Fail" severity error;')
print("op_code <=s_teq;")
print("wait for 10 ns;")
print('assert res = x"' + tohex(a ^ b, '08x') +'" report "Fail" severity error;')
print("op_code <=s_cmp;")
print("wait for 10 ns;")
print('assert res = x"' + tohex(a -b, '08x') +'" report "Fail" severity error;')
print("op_code <=s_cmn;")
print("wait for 10 ns;")
print('assert res = x"' + tohex(a + b, '08x') +'" report "Fail" severity error;')
print("op_code <=s_orr;")
print("wait for 10 ns;")
print('assert res = x"' + tohex(a|b, '08x') +'" report "Fail" severity error;')
print("op_code <=s_mov;")
print("wait for 10 ns;")
print('assert res = x"' + tohex(b, '08x') +'" report "Fail" severity error;')
print("op_code <=s_bic;")
print("wait for 10 ns;")
print('assert res = x"' + tohex(a & ~b, '08x') +'" report "Fail" severity error;')
print("op_code <=s_mvn;")
print("wait for 10 ns;")
print('assert res = x"' + tohex(~b, '08x') +'" report "Fail" severity error;')